apiVersion: apps/v1
kind: Deployment
metadata:
  name: xflats
  labels:
    app: xflats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xflats
  template:
    metadata:
      labels:
        app: xflats
    spec:
      containers:
      - name: scraper-otodom
        image: scraper_otodom:1.0.0
        volumeMounts:
        - name: gcpfirestore
          mountPath: "/etc/gcpfirestore"
          readOnly: true
        resources:
          limits:
            cpu: "300m"
            memory: "512Mi"
            ephemeral-storage: "512M"
      - name: redis
        image: redis:buster
        ports:
          - containerPort: 6379
      volumes:
      - name: gcpfirestore
        secret:
          secretName: gcp-firestore-dm7t9h22dh
