#Use root/example as user/password credentials
version: '3.1'

services:

  scraperotodom:
    build: ./app_webscr_otodom
    image: scraperotodom:1
    restart: on-failure
    environment:
      SCRAPER_START_DELAY_SEC: 30
      SCRAPER_DELAY_AFTER_EACH_RUN_SEC: 180
    depends_on:
      - mongo
    networks:
      - webnet

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: Otodom
      MONGO_INITDB_ROOT_USERNAME: xflats
      MONGO_INITDB_ROOT_PASSWORD: xflats
      #docker run -p 27017:27017 -e "MONGO_INITDB_DATABASE=Otodom" -e "MONGO_INITDB_ROOT_USERNAME=xflats" -e "MONGO_INITDB_ROOT_PASSWORD=xflats" mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db:/data/db
    networks:
      - webnet

networks: 
  webnet:

#docker-compose build
#docker-compose up
#docker system prune
