#Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.2.0-bionic
    restart: always
    environment:
      MONGO_INITDB_DATABASE: OFFERS
      MONGO_INITDB_ROOT_USERNAME: xflats
      MONGO_INITDB_ROOT_PASSWORD: xflats
      #docker run -p 27017:27017 -e "MONGO_INITDB_DATABASE=OFFERS" -e "MONGO_INITDB_ROOT_USERNAME=xflats" -e "MONGO_INITDB_ROOT_PASSWORD=xflats" mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db:/data/db
    networks:
      - webnet

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    ports:
      - "2181:2181"
    networks:
      - webnet

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "otodom:1:1,olx:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webnet

  nify:
    image: apache/nifi:1.9.2
    restart: always
    ports:
      - 9090:9090
    environment:
      NIFI_WEB_HTTP_PORT: 9090
    volumes:
      - ./nify/conf:/opt/nifi/nifi-current/conf/
    networks:
      - webnet

  mlmodel:
    build: ./app_mlmodel
    image: app_mlmodel:0.0.1
    restart: always
    ports:
      - 8080:8080
    networks:
      - webnet

  scraper_otodom:
    build:
      context: ./app_web
      dockerfile: Dockerfile_otodom
    image: app_scraper_otodom:0.0.1
    restart: always
    volumes:
      - ./app_web/scraper/settings.py:/app/scraper/settings.py
      - ./app_web/scraper/spiders/xhpats.json:/app/scraper/spiders/xhpats.json
    environment:
      SCRAPER_START_DELAY_SEC: 60
      SCRAPER_DELAY_AFTER_EACH_RUN_SEC: 180
    depends_on:
      - mongo
      - zookeeper
      - kafka
    networks:
      - webnet

  scraper_olx:
    build:
      context: ./app_web
      dockerfile: Dockerfile_olx
    image: app_scraper_olx:0.0.1
    restart: always
    volumes:
      - ./app_web/scraper/settings.py:/app/scraper/settings.py
      - ./app_web/scraper/spiders/xhpats.json:/app/scraper/spiders/xhpats.json
    environment:
      SCRAPER_START_DELAY_SEC: 60
      SCRAPER_DELAY_AFTER_EACH_RUN_SEC: 180
    depends_on:
      - mongo
      - zookeeper
      - kafka
    networks:
      - webnet

  scraper_gratka:
    build:
      context: ./app_web
      dockerfile: Dockerfile_gratka
    image: app_scraper_gratka:0.0.1
    restart: always
    volumes:
      - ./app_web/scraper/settings.py:/app/scraper/settings.py
      - ./app_web/scraper/spiders/xhpats.json:/app/scraper/spiders/xhpats.json
    environment:
      SCRAPER_START_DELAY_SEC: 60
      SCRAPER_DELAY_AFTER_EACH_RUN_SEC: 180
    depends_on:
      - mongo
      - zookeeper
      - kafka
    networks:
      - webnet

networks:
  webnet:
