#Use root/example as user/password credentials
version: '3.1'

services:

  scraperotodom:
    build: ./app_webscr_otodom
    image: scraperotodom:1
    restart: always
    volumes:
      - ./app_webscr_otodom/scraper/settings.py:/app/scraper/settings.py
      - ./app_webscr_otodom/scraper/spiders/xhpats.json:/app/scraper/spiders/xhpats.json
    environment:
      SCRAPER_START_DELAY_SEC: 30
      SCRAPER_DELAY_AFTER_EACH_RUN_SEC: 180
    depends_on:
      - mongo
      - zookeeper
      - kafka
    networks:
      - webnet

  mongo:
    image: mongo:4.2.0-bionic
    restart: always
    environment:
      MONGO_INITDB_DATABASE: Otodom
      MONGO_INITDB_ROOT_USERNAME: xflats
      MONGO_INITDB_ROOT_PASSWORD: xflats
      #docker run -p 27017:27017 -e "MONGO_INITDB_DATABASE=Otodom" -e "MONGO_INITDB_ROOT_USERNAME=xflats" -e "MONGO_INITDB_ROOT_PASSWORD=xflats" mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db:/data/db
    networks:
      - webnet

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - webnet

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost 
      KAFKA_CREATE_TOPICS: "xflats:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webnet

networks: 
  webnet:

