#Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: Otodom
      MONGO_INITDB_ROOT_USERNAME: xflats
      MONGO_INITDB_ROOT_PASSWORD: xflats
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db:/data/db    
    networks:
      - webnet      
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: xflats 
      ME_CONFIG_MONGODB_ADMINPASSWORD: xflats 
    networks:
      - webnet 
  
networks: 
  webnet:
