AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  producerOtodomList:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_functions.test
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 300
      Role: 'arn:aws:iam::464312940617:role/lambda-s3-role'