#Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.2.0-bionic
    restart: always
    environment:
      MONGO_INITDB_DATABASE: OFFERS
      MONGO_INITDB_ROOT_USERNAME: xflats
      MONGO_INITDB_ROOT_PASSWORD: xflats
      #docker run -p 27017:27017 -e "MONGO_INITDB_DATABASE=Otodom" -e "MONGO_INITDB_ROOT_USERNAME=xflats" -e "MONGO_INITDB_ROOT_PASSWORD=xflats" mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      - webnet

  redis:
    image: redis:buster
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - webnet

networks:
  webnet:
