apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model
  labels:
    app: ml-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
      - name: ml-model
        image: app_mlmodel:1.0.0
        ports:
          - containerPort: 8666
            name: tcp-8666
            protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: "1024Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: ml-model
spec:
  selector:
    app: ml-model
  type: NodePort #https://kubernetes.io/docs/concepts/services-networking/service/#nodeport
                 #https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  ports:
    - port: 8666
      targetPort: 8666
      nodePort: 31866
      protocol: TCP
      name: tcp-8666
