# docker exec -it <container> /bin/bash

version: '3.7'

services:

  redis:
    image: redis:buster
    container_name: redis
    restart: always
    env_file: ../secrets/mongo.env
    ports:
      - 6379:6379
    networks:
      - webnet

networks:
  webnet:
